name: Sync from Google Sheets

on:
  push:
    branches:
      - "rewrite-fetch-tricks-action"


env:
  GITHUB_HEAD_REF: "origin/rewrite"
  TARGET_REPOSITORY: ${{ github.repository }}


permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    name: Sync Data from Google Sheets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Prepare the Branch
        run: |
          # Check into the "main" branch (currently rewrite)
          echo A
          git checkout $GITHUB_HEAD_REF
          echo B
          git pull

          # Check if a "chore/sheets" Branch does not exists.
          if [ ! -z $(git branch --list --remotes origin/chore/sheets) ]
          then
            echo C

            # Create if it is missing
            git checkout -b chore/sheets
          fi
          echo D

          git checkout chore/sheets
          echo E
          
          git pull

          # If here: Branch exists. But might still have a bad state.
          # Merge from rewrite and favour their (rewrite) changes on conflicts
          git merge $GITHUB_HEAD_REF -X theirs

          # If here: Branch set up and will (hopefully :P) not create any issues on changes
      - name: Install Dependencies from Lock-File
        run: npm ci
      - name: Sync with the Sheet
        run: npx vite-node ./scripts/fetchFromSheet.ts
        # Sync with the Sheet has created some changes. For the next step these changes have to be staged,
        # otherwise the diffing will not work
      - name: Add YAML Changes to Git
        run: git add src/data
      - name: Run the PR Procedure
        run: npx vite-node ./scripts/createPrForSheetsIfNeeded.ts
